const PostData =[

    {
      id: 0,
      title: 'How Spotify ran the largest Google Dataflow job ever for Wrapped 2019',
        Date: 'February 18, 2020,' ,
        front: 'In early December, Spotify  launched its annual personalized Wrapped playlist with its users’ most-streamed sounds of 2019. That has become a bit of a tradition and isn’t necessarily anything new, but for 2019, it also gave users a look back at how they used Spotify over the last decade. Because this was quite a large job, Spotify gave us a bit of a look under the covers of how it generated these lists for its ever-growing number of free and paid subscribers.',
        blog: 'It’s no secret that Spotify is a big Google  Cloud Platform user. Back in 2016, the music streaming service publicly said that it was going to move to Google Cloud, after all, and in 2018, it disclosed that it would spend at least $450 million on its Google Cloud infrastructure in the following three years.It was also back in 2018, for that year’s Wrapped, that Spotify ran the largest Google Cloud Dataflow job ever run on the platform, a service the company started experimenting with a few years earlier. “Back in 2015, we built and open-sourced a big data processing Scala API for Apache Beam and Google Cloud Dataflow called Scio,” Spotify’s VP of Engineering Tyson Singer told me. “We chose Dataflow over Dataproc because it scales with less operational overhead and Dataflow fit with our expected needs for streaming processing. Now we have a great open-source toolset designed and optimized for Dataflow, which in addition to being used by most internal teams, is also used outside of Spotify.”For Wrapped 2019, which includes the annual and decadal lists, Spotify ran a job that was five times larger than in 2018 — but it did so at three-quarters of the cost. Singer attributes this to his team’s familiarity with the platform. “With this type of global scale, complexity is a natural consequence. By working closely with Google Cloud’s engineering teams and specialists and drawing learnings from previous years, we were able to run one of the most sophisticated Dataflow jobs ever written.” Still, even with this expertise, the team couldn’t just iterate on the full data set as it figured out how to best analyze the data and use it to tell the most interesting stories to its users. “Our jobs to process this would be large and complex; we needed to decouple the complexity and processing in order to not overwhelm Google Cloud Dataflow,” Singer said. “This meant that we had to get more creative when it came to going from idea, to data analysis, to producing unique stories per user, and we would have to scale this in time and at or below cost. If we weren’t careful, we risked being wasteful with resources and slowing down downstream teams.” To handle this workload, Spotify not only split its internal teams into three groups (data processing, client-facing and design, and backend systems), but also split the data processing jobs into smaller pieces. That marked a very different approach for the team. “Last year Spotify had one huge job that used a specific feature within Dataflow called “Shuffle.” The idea here was that having a lot of data, we needed to sort through it, in order to understand who did what. While this is quite powerful, it can be costly if you have large amounts of data.”',
        img: "https://techcrunch.com/wp-content/uploads/2020/02/GettyImages-1201614834.jpg?w=1390&crop=1"
    },
    {
      id: 1,
        Date: 'February 4, 2020',
      title: 'This simple formula tells you how long it will take for your money to double—while you sit back and relax',
      front: 'If you put your money in the right places, it can grow substantially over time, thanks to the power of compound interest. It could even double, while you don’t have to do a thing.',
      blog: 'Want to figure out just how fast your money could grow? The “Rule of 72” approximates how many years it will take for your money to double, given a fixed rate of return." “Think about your savings for the future,” Tom Mathews and Steve Siebold write in their book “How Money Works,” which highlights the “Rule of 72” as of one of three essential personal finance topics to understand (the other two being compound interest and the time value of money). “The Rule of 72 can give you an idea of how many doubles you’ll get in your lifetime. With more time, a lower interest rate may give you enough to nail your goals. With less time, you may need a higher interest rate.” The formula is simple: 72 / interest rate = years to double. Try plugging in various interest rates from the different accounts your money is in, from savings and money market accounts to index and mutual funds. For example, if your account earns: 1%, it will take 72 years for your money to double (72 / 1 = 72), 3%, it will take 24 years for your money to double (72 / 3 = 24), 6%, it will take 12 years for your money to double (72 / 6 = 12), 9%, it will take 8 years for your money to double (72 / 9 = 8), 12%, it will take 6 years for your money to double (72 / 12 = 6). If your money sits in a standard savings account and earns just 0.09% (the average interest rate for savings accounts nationwide), it would take 800 years to double. If you have extra savings, you’re probably better off keeping it in a high-yield savings account or certificate of deposit, which both offer significantly higher interest rates, up to 2.69%. If you invest your money in the stock market, whether through an employer-sponsored 401(k) plan, a traditional or Roth IRA, an individual brokerage account or somewhere else, you’ll likely see even bigger returns. The average annualized total return for the S&P 500 index over the past 90 years is 9.8%. Adjusted for inflation, it still comes to an annual return of around 7% to 8%. If you earn 7%, your money will double in a little over 10 years.',
      img: 'https://image.cnbcfm.com/api/v1/image/106359706-1580238825150spring-time-girl-smiling-laying-in-flowers_t20_xxro9l.jpg?v=1580238928&w=1400&h=950'
    },
    {
      id: 2,
      title: '7 telemedicine services offering free health care during the coronavirus pandemic',
        Date: 'April 17, 2020',
      front: 'Over the past month, a staggering 22 million Americans filed for unemployment as cities and states around the country continue to order Americans to shelter in place in an attempt to mitigate the public health effects of the coronavirus.',
      blog: 'In the U.S., unemployment during a health crisis can be especially challenging since about 49% of Americans get health insurance through their employer. As many as 9.2 million workers are at risk of losing their employer-provided health insurance, according to the latest estimates from the Economic Policy Institute. To help fill that gap, telemedicine companies are offering check-ups and other services for free or at discounted rates. Honeybee Health found several telehealth companies offering discounted services, ranging from $15 to $89. CNBC Make It confirmed that seven telemedicine companies are offering completely free virtual doctor’s visits for those affected by the coronavirus, although some restrictions do apply. We will continue to update if more providers offer free options. They are 1.CareClix ,2.Callondoc 3.Galileo Health ,4.HeyDoctor by GoodRx ,5.K Health ,6.One Medical ,7.SteadyMD.',
      img: "https://image.cnbcfm.com/api/v1/image/106491963-1587052157244gettyimages-1062130130.jpeg?v=1587052208&w=1400&h=950"
    }
  ]
  export default PostData
 

  